[package]
name = "floating-ui-yew-example"
description = "Example for Floating UI Yew."
publish = false

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
console_error_panic_hook.workspace = true
console_log.workspace = true
floating-ui-yew = { path = ".." }
log.workspace = true
wasm-bindgen.workspace = true
web-sys.workspace = true
yew = { workspace = true, features = ["csr"] }
