[package]
name = "floating-ui-yew"
description = "Floating UI for Yew."
homepage = "https://floating-ui.rustforweb.org/frameworks/yew.html"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
floating-ui-dom = { path = "../dom", version = "0.1.3" }
yew.workspace = true
web-sys.workspace = true

[dev-dependencies]
wasm-bindgen-test.workspace = true
