[package]
name = "floating-ui-dom"
description = "Rust port of Floating UI. Floating UI for the web."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
floating-ui-core = { path = "../core", version = "0.0.1" }
floating-ui-utils = { path = "../utils", version = "0.0.1", features = ["dom"] }
web-sys.workspace = true
