[package]
name = "floating-ui-core"
description = "Rust port of Floating UI. Positioning library for floating elements: tooltips, popovers, dropdowns, and more."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
dyn-clone.workspace = true
floating-ui-utils = { path = "../utils", version = "0.0.5" }
serde.workspace = true
serde_json.workspace = true
