[package]
name = "floating-ui-leptos"
description = "Floating UI for Leptos."
homepage = "https://floating-ui.rustforweb.org/frameworks/leptos.html"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
dyn_derive.workspace = true
dyn_std.workspace = true
floating-ui-dom.workspace = true
leptos.workspace = true
leptos-node-ref.workspace = true
send_wrapper.workspace = true
web-sys.workspace = true

[dev-dependencies]
wasm-bindgen-test.workspace = true
