[package]
name = "floating-ui-leptos"
description = "Floating UI for Leptos."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
cfg-if = "1.0.0"
floating-ui-dom = { path = "../dom", version = "0.0.9" }
leptos = { version = "0.6.12" }
paste = "1.0.0"
web-sys.workspace = true

[dev-dependencies]
wasm-bindgen-test.workspace = true
