[package]
name = "floating-ui-leptos-example"
description = "Example for Floating UI Leptos."
publish = false

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
console_error_panic_hook.workspace = true
console_log.workspace = true
floating-ui-leptos = { path = ".." }
leptos = { workspace = true, features = ["csr"] }
log.workspace = true
wasm-bindgen.workspace = true
web-sys.workspace = true
