[package]
name = "floating-ui-leptos-example"
description = "Example for Floating UI Leptos."
publish = false

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
console_error_panic_hook.workspace = true
console_log.workspace = true
floating-ui-leptos.workspace = true
leptos = { workspace = true, features = ["csr"] }
leptos-node-ref.workspace = true
log.workspace = true
send_wrapper.workspace = true
